### ISSUE TITLE
Little error in HBaseWriter.java with "via"

### ISSUE THREAD

**Issue by LetMeR00t** [OpenSourceMasters/hbase-writer#16]
Hello,
I found this little error in "HBaseWriter.java", this is the current code :

addSerializedDataToPut(put, getHbaseParameters().getCuriColumnFamily(), getHbaseParameters().getViaColumnName(), curi.getVia() != null ? curi.toString() : null);

It would be :

addSerializedDataToPut(put, getHbaseParameters().getCuriColumnFamily(), getHbaseParameters().getViaColumnName(), curi.getVia() != null ? curi.getVia().toString() : null);

Thanks for the code which is very clear.

**Comment by OpenSourceMasters** [comment]
Thanks for catching this, good eye!  Changes have been made and are now pushed into the 'master' branch.
